input {
  kafka {
    bootstrap_servers => "localhost:9092"
    topics => ["logs"]
    codec => json
    group_id => "logstash-logs"
  }
  kafka {
    bootstrap_servers => "localhost:9092"
    topics => ["metrics"]
    codec => json
    group_id => "logstash-metrics"
  }
}

filter {
  if [agent][type] == "metricbeat" {
    mutate {
      add_field => { "[@metadata][target_index]" => "metricbeat-kafka-%{+YYYY.MM.dd}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][target_index]" => "logs-kafka-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "%{[@metadata][target_index]}"
    action => "create"
  }
}
