input {
  file {
    path => "/var/ossec/logs/alerts/alerts.json"
    codec => json
    type => "wazuh-alerts"
  }
}
filter {
  if [type] == "wazuh-alerts" {
    mutate {
      add_field => { "[@metadata][index]" => "wazuh-alerts" }
    }
  }
}
output {
  if [type] == "wazuh-alerts" {
    elasticsearch {
      hosts => ["http://localhost:9200"]
      index => "wazuh-alerts-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "sat_elastic_2026"
    }
  }
}
