metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - memory
      - network
      - diskio
      - filesystem
      - process
      - process_summary
      - uptime
      - load
    enabled: true
    period: 30s
    processes: ['.*']

  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    enabled: true
    period: 30s

output.kafka:
  hosts: ["192.168.87.132:9093"]
  topic: "metrics"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000



logging.level: info
